### ISSUE TITLE
Test cases not passing

### ISSUE THREAD

**Issue by kingsleytorlowei** [architect/functions-python#2]
**Describe the issue**
All the test cases fail when ``` for i in `ls tests/test_*`; do python3 $i; done ``` is run . Most of the errors point to the reflect function in 
https://github.com/architect/functions-python/blob/master/arc/__init__.py 
I'll like to know more about the ARC_CLOUDFORMATION environment variable used in this code

**Comment by ryanblock** [comment]
Ah! `ARC_CLOUDFORMATION` is the CloudFormation app ID used to look up the app in AWS's index of a given org account's CloudFormation stacks.

In a purely unit testing-only env any value would be fine. However, that function's only job is to touch live AWS infra, so to test it would likely imply an integration test and require live infra to query.

I'm open to suggestions on how we handle this!
