### ISSUE TITLE
ARC_CLOUDFORMATION is deprecated in Architect, but still used here

### ISSUE THREAD

**Issue by scoates** [architect/functions-python#20]
**Describe the issue**
The [upgrade guide](https://github.com/architect/arc.codes/blob/9ca38e098e74132824cdd93f9aeedc1bb313ed7a/src/views/docs/en/about/upgrade-guide.md) for [Architect](https://github.com/architect/arc.codes) says `ARC_CLOUDFORMATION` is deprecated, but the Python tooling still uses it (and without guarding): https://github.com/architect/functions-python/blob/796e7661afa069c3a2f7bc609fd0c0af512244cb/arc/__init__.py

**Steps to reproduce**
1. Follow the getting started guide on arc.codes
2. Try to run a Python function/endpoint that uses `arc.reflect()`
3. The route fails with (something like):

```
Traceback (most recent call last):
  File "", line 1, in 
  File "/Users/sean/src/fwiki/fwiki/src/http/get-index/index.py", line 6, in handler
    return {'body': json.dumps(arc.reflect())}
  File "/Users/sean/src/fwiki/fwiki/src/http/get-index/vendor/arc/__init__.py", line 5, in reflect
    path = '/' + os.environ['ARC_CLOUDFORMATION']
  File "/nix/store/gxnjdv4v6z21n2g5hp4cnnlcysaqcv83-python3-3.9.12/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'ARC_CLOUDFORMATION'
```

**Expected behavior**
The Python functions to be more in sync with the Architect docs (I'm not sure how to trick `.reflect()` into working right now, at all).

**Additional context**
(I don't think this is particularly relevant here, but): This is Python 3.9 via pipenv dependencies installed with nix.

**Comment by ryanblock** [comment]
Sadly this lib was allowed to get woefully out of date, and I failed to lead the way on the open source / community side to keep things moving here.

Time's come to get this thing fixed up and properly maintained, so I'll be personally spending the next little while here getting it back into shape. Apologies in advance for all the crappy Python that I'll be landing here in short order. 😅 

We'll def be getting this issue closed!

**Comment by scoates** [comment]
I expected the outcome of this to be more like "turns out we're dropping Python support", so this is good news, even with the delay.
